from collections import defaultdict
from pathlib import Path
from typing import List

from general_utilities.association_resources import (
    process_snp_or_gene_tar,
    build_transcript_table,
    get_gene_id,
    process_gene_or_snp_wgs
)
from general_utilities.import_utils.import_lib import TarballType
from general_utilities.mrc_logger import MRCLogger

from extract.extract_association_pack import ExtractAssociationPack
from extract.gene_extraction import GeneExtractionPipeline


class ExtractVariants:
    """
    Main extraction class.

    Gene extraction from tarballs (requires association_tarballs + gene IDs)
    - Standard gene-based tarballs
    - Non-standard SNP/GENE tarballs
    """

    def __init__(self, output_prefix: str, association_pack: ExtractAssociationPack):
        self._logger = MRCLogger(__name__).get_logger()
        self._outputs = []
        self._output_prefix = output_prefix
        self._association_pack = association_pack

        # Initialize data structures
        self.genetic_map = defaultdict(list)

        # Build transcripts table
        self._transcripts_table = build_transcript_table(
            transcripts_path=self._association_pack.transcript_index
        )

        # Route based on what was provided
        if self._association_pack.tarball_type in (TarballType.SNP, TarballType.GENE):
            self._initialize_nonstandard_tarball()
        elif self._association_pack.gene_ids is not None:
            self._initialize_gene_extraction()

    def _initialize_nonstandard_tarball(self):
        """
        Initialize for SNP or GENE tarball extraction.

        These tarballs contain pre-defined SNP or gene lists rather than
        gene-based masks.
        """
        self._logger.info("Initializing non-standard tarball extraction (SNP/GENE tar)")

        gene_info, returned_chromosomes = process_snp_or_gene_tar(
            self._association_pack.tarball_type == TarballType.SNP,
            self._association_pack.tarball_type == TarballType.GENE,
            self._association_pack.tarball_prefixes[0]
        )

        for chromosome in returned_chromosomes:
            self.genetic_map[chromosome].append(gene_info)

    def _initialize_gene_extraction(self):
        """
        Initialize for standard gene extraction from gene-based tarballs.

        Handles gene symbols and ENST IDs by looking them up in the tarball structure.
        """
        self._logger.info("Initializing gene extraction from tarballs")

        for gene_id in self._association_pack.gene_ids:
            # get_gene_id handles gene symbols and ENST IDs
            gene_info = get_gene_id(gene_id, self._transcripts_table)

            # Search for this gene across all chunks
            for chunk in self._association_pack.bgen_dict:
                try:
                    chromosomes = process_gene_or_snp_wgs(
                        identifier=gene_info.name,
                        tarball_prefix=self._association_pack.tarball_prefixes[0],
                        chunk=chunk
                    )
                except FileNotFoundError:
                    self._logger.debug(f"Variant table for chunk {chunk} not found, skipping.")
                    continue

                if chromosomes:
                    self._logger.info(
                        f"{gene_info['SYMBOL']} found in {chunk} "
                        f"({', '.join(chromosomes)})"
                    )
                    self.genetic_map[chunk].append(gene_info)

    def run_tool(self):
        """Execute the appropriate extraction pipeline."""
        self._logger.info("Running gene extraction pipeline...")
        pipeline = GeneExtractionPipeline(
            output_prefix=self._output_prefix,
            association_pack=self._association_pack,
            genetic_map=self.genetic_map,
            transcripts_table=self._transcripts_table
        )

        self._outputs = pipeline.run()

    def get_outputs(self) -> List[Path]:
        """
        Get a list of output files generated by the extraction.

        :return: List of Path objects for all output files
        """
        return self._outputs
