from pathlib import Path
from typing import List

from general_utilities.association_resources import (
    process_snp_or_gene_tar,
    build_transcript_table,
    get_gene_id,
    process_gene_or_snp_wgs
)
from general_utilities.mrc_logger import MRCLogger

from extract.extract_association_pack import ExtractAssociationPack
from extract.gene_extraction import GeneExtractionPipeline


class ExtractVariants:
    """
    Main extraction class that routes to the gene extraction pipeline.

    Supports two gene-driven extraction modes:
    1. Standard gene extraction from gene-based tarballs (requires association_tarballs + gene IDs)
    2. Non-standard SNP/GENE tarball extraction (tarballs contain SNP or gene lists directly)
    """

    def __init__(self, output_prefix: str, association_pack: ExtractAssociationPack):
        self._logger = MRCLogger(__name__).get_logger()
        self._outputs = []
        self._output_prefix = output_prefix
        self._association_pack = association_pack

        # Initialize data structures
        self._gene_infos = []
        self._gene_chunk_map = []
        self._chromosomes = set()

        # Build transcripts table
        self._transcripts_table = build_transcript_table(
            transcripts_path=self._association_pack.transcript_index
        )

        # Route based on what was provided
        if self._association_pack.is_non_standard_tar:
            self._initialize_nonstandard_tarball()
        else:
            self._initialize_gene_extraction()

    def _initialize_nonstandard_tarball(self):
        """
        Initialize for SNP or GENE tarball extraction.

        These tarballs contain pre-defined SNP or gene lists rather than
        gene-based masks.
        """
        self._logger.info("Initializing non-standard tarball extraction (SNP/GENE tar)")

        gene_info, returned_chromosomes = process_snp_or_gene_tar(
            self._association_pack.is_snp_tar,
            self._association_pack.is_gene_tar,
            self._association_pack.tarball_prefixes[0]
        )

        self._gene_infos.append(gene_info)
        self._chromosomes = returned_chromosomes

        for chromosome in self._chromosomes:
            self._gene_chunk_map.append((gene_info, chromosome))

    def _initialize_gene_extraction(self):
        """
        Initialize for standard gene extraction from gene-based tarballs.

        Handles gene symbols and ENST IDs by looking them up in the tarball structure.
        """
        self._logger.info("Initializing gene extraction from tarballs")

        for gene_id in self._association_pack.gene_ids:
            # get_gene_id handles gene symbols and ENST IDs
            gene_info = get_gene_id(gene_id, self._transcripts_table)
            self._gene_infos.append(gene_info)

            # Search for this gene across all chunks
            for chunk in self._association_pack.bgen_dict:
                chromosomes = process_gene_or_snp_wgs(
                    identifier=gene_info.name,
                    tarball_prefix=self._association_pack.tarball_prefixes[0],
                    chunk=chunk
                )

                if chromosomes:
                    self._logger.info(
                        f"{gene_info['SYMBOL']} found in {chunk} "
                        f"({', '.join(chromosomes)})"
                    )
                    self._chromosomes.add(chunk)
                    self._gene_chunk_map.append((gene_info, chunk))

    def run_tool(self):
        """Execute the appropriate extraction pipeline."""
        self._logger.info("Running gene extraction pipeline...")
        pipeline = GeneExtractionPipeline(
            output_prefix=self._output_prefix,
            association_pack=self._association_pack,
            gene_infos=self._gene_infos,
            gene_chunk_map=self._gene_chunk_map,
            chromosomes=self._chromosomes,
            transcripts_table=self._transcripts_table
        )

        self._outputs = pipeline.run()

    def get_outputs(self) -> List[Path]:
        """
        Get a list of output files generated by the extraction.

        :return: List of Path objects for all output files
        """
        return self._outputs
