import csv
import json
from collections import defaultdict
from csv import DictWriter
from dataclasses import asdict
from pathlib import Path
from typing import List, Tuple, Dict

import dxpy
import numpy as np
import pandas as pd
from bgen import BgenReader
from general_utilities.association_resources import bgzip_and_tabix
from general_utilities.bgen_utilities.genotype_matrix import generate_csr_matrix_from_bgen, make_variant_list
from general_utilities.import_utils.file_handlers.export_file_handler import ExportFileHandler
from general_utilities.import_utils.file_handlers.input_file_handler import InputFileHandler
from general_utilities.import_utils.import_lib import LOGGER, TarballType
from general_utilities.job_management.command_executor import build_default_command_executor
from general_utilities.job_management.joblauncher_factory import joblauncher_factory
from general_utilities.job_management.thread_utility import ThreadUtility
from general_utilities.linear_model import linear_model
from general_utilities.linear_model.linear_model import LinearModelResult
from general_utilities.linear_model.proccess_model_output import merge_glm_staar_runs, process_model_outputs
from general_utilities.linear_model.staar_model import staar_null, staar_genes, load_staar_genetic_data
from general_utilities.mrc_logger import MRCLogger
from scipy.io import mmwrite

from extract.extract_association_pack import ExtractAssociationPack


class GeneExtractionPipeline:
    """A pipeline for extracting gene-based information and running association tests.

    This class orchestrates the process of identifying variants within specific genes,
    extracting their genotype information, and running both standard linear models
    and STAAR models for association testing.

    :param output_prefix: A prefix for all output files generated by this pipeline.
    :param association_pack: A container for input data and parameters.
    :param genetic_map: A dictionary mapping chromosomes to gene information.
    :param transcripts_table: A pandas DataFrame containing transcript information.
    """

    def __init__(self, output_prefix: str, association_pack: ExtractAssociationPack,
                 genetic_map: dict, transcripts_table: pd.DataFrame):
        self._logger = MRCLogger(__name__).get_logger()
        self._output_prefix = output_prefix
        self._association_pack = association_pack
        self._genetic_map = genetic_map
        self._transcripts_table = transcripts_table
        self._outputs: List[Path] = []
        self._gene_variant_map: Dict = defaultdict(dict)

    def run(self) -> List[Path]:
        """Runs the entire gene extraction and association testing pipeline.

        This method orchestrates the full workflow:
        1. Downloads VEP annotations.
        2. Builds a map of genes to variants.
        3. Extracts variant and carrier information for each gene.
        4. Runs linear and STAAR association models.
        5. Merges and finalises all outputs.

        :return: A list of paths to the generated output files.
        """
        self._logger.info("Loading VEP annotations...")
        vep_file_map = self._download_vep()

        self._logger.info("Building gene-variant map...")
        self._build_gene_variant_map()

        self._logger.info("Extracting variant information...")
        self._collect_variant_information(vep_file_map)

        self._logger.info("Running linear models...")
        self._run_linear_models()
        self._run_staar_models()

        merged_outputs = merge_glm_staar_runs(self._output_prefix,
                                              self._association_pack.tarball_type == TarballType.SNP,
                                              self._association_pack.tarball_type == TarballType.GENE)

        self._outputs.extend(merged_outputs)

        self._outputs.append(self._export_phenotypes())

        return self._outputs

    def _build_gene_variant_map(self):
        """Builds a dictionary mapping genes to their variants.

        This method iterates through all tarball prefixes and chromosomes, reads the
        STAAR variants table for each, and uses the `make_variant_list` utility
        to create a comprehensive map. This map is stored in the instance variable
        `self._gene_variant_map`.
        """
        for tarball_prefix in self._association_pack.tarball_prefixes:
            for chromosome in self._genetic_map.keys():
                variants_table_path = f'{tarball_prefix}.{chromosome}.STAAR.variants_table.tsv'
                if Path(variants_table_path).exists():
                    variants_df = pd.read_csv(variants_table_path, sep='\t')
                    self._gene_variant_map[tarball_prefix][chromosome] = make_variant_list(variants_df)
                else:
                    self._logger.warning(f'Could not find STAAR variants table {variants_table_path}')

    def _download_vep(self) -> Dict[str, Path]:
        """Downloads VEP annotation files for each chromosome chunk.

        The method retrieves the VEP file handles from the association pack and
        renames them locally for subsequent use.

        :return: A dictionary mapping chunk_key (chromosome) to the path of the downloaded VEP file.
        """
        vep_file_paths: Dict[str, Path] = {}
        for chunk_key in self._genetic_map.keys():
            vep_dx = self._association_pack.bgen_dict[chunk_key]['vep']
            output_filename = Path(f"{chunk_key}.filtered.vep.tsv.gz")
            vep_dx.get_file_handle().rename(output_filename)
            vep_file_paths[chunk_key] = output_filename
        return vep_file_paths

    def _collect_variant_information(self, vep_file_map: Dict[str, Path]) -> None:
        """Collects variant and carrier information for all genes in parallel.

        This method sets up a thread pool and launches a parallel job for each
        gene via the `_annotate_variants` method. After all jobs are complete,
        it gathers the paths of the generated output files.

        :return: A list of paths to the generated output files.
        """
        outputs = []
        thread_utility = ThreadUtility(self._association_pack.threads, thread_factor=2)

        for chromosome, gene_infos in self._genetic_map.items():
            for gene_info in gene_infos:
                for tarball_prefix in self._association_pack.tarball_prefixes:
                    thread_utility.launch_job(
                        function=self._annotate_variants,
                        inputs={
                            'tarball_prefix': tarball_prefix,
                            'gene_info': gene_info,
                            'chromosomes': chromosome,
                            'vep_file_map': vep_file_map
                        },
                        outputs=['variant_file', 'carriers_file']
                    )
        thread_utility.submit_and_monitor()

        for result in thread_utility:
            self._outputs.append(result['variant_file'])
            self._outputs.append(result['carriers_file'])

    def _annotate_variants(self, tarball_prefix: str, gene_info: pd.Series,
                           chromosomes: str, vep_file_map: Dict[str, Path]) -> Tuple[Path, Path]:
        """
        Annotates variants for a single gene and chromosome combination.

        This method processes BGEN files to extract genotype and carrier information for the specified gene and chromosome.
        It matches variants to the gene, calculates allele counts and frequencies, merges with VEP annotations, and exports
        the results to output files.

        :param tarball_prefix: The tarball prefix for the current data chunk.
        :param gene_info: A pandas Series containing information about the gene (including ENST ID and symbol).
        :param chromosomes: The chromosome identifier for the current gene.
        :return: A list containing the paths to the variant and carrier output files, or [None, None] if no variants found.
        """

        # Setup Inputs
        gene_symbol = gene_info['SYMBOL']
        enst_id = gene_info.name

        # Get raw variants from input map
        gene_data = self._gene_variant_map.get(tarball_prefix, {}).get(chromosomes, {}).get(enst_id)
        raw_variant_list = set(gene_data['vars'])
        target_variants = raw_variant_list

        # Output Files
        variant_file = Path(f'{self._output_prefix}.{tarball_prefix}.{gene_symbol}.variant_table.tsv')
        carriers_file_path = Path(f'{self._output_prefix}.{tarball_prefix}.{gene_symbol}.carriers_formatted.tsv')

        # BGEN Setup
        search_chrom = gene_data['chrom']
        start = gene_data['min']
        end = gene_data['max']
        bgen_dict = self._association_pack.bgen_dict[chromosomes]
        bgen_handle = bgen_dict['bgen'].get_file_handle()
        sample_handle = bgen_dict['sample'].get_file_handle()
        _ = bgen_dict['index'].get_file_handle()  # Keep reference alive

        variant_info = []

        self._logger.info(f"Looking for {len(target_variants)} variants in range {search_chrom}:{start}-{end}.")

        with BgenReader(bgen_handle, sample_handle) as bgen_reader, open(carriers_file_path, 'w') as carriers_file:
            # make into strings
            carriers_dict = csv.DictWriter(
                carriers_file,
                fieldnames=['CHROM', 'POS', 'varID', 'REF', 'ALT', 'IID', 'GT'],
                delimiter="\t"
            )
            carriers_dict.writeheader()

            samples = np.array(bgen_reader.samples)
            variant_iterator = bgen_reader.fetch(search_chrom, start=start, stop=end)
            for variant in variant_iterator:
                if variant.rsid in target_variants:
                    self._process_variant_dosage(variant, samples, variant_info, carriers_dict)

        # Process VEP Data & Export
        geno_table = pd.DataFrame(variant_info,
                                  columns=['varID', 'MAF_tested', 'AC_tested', 'AC_tested_Het', 'AC_tested_Hom'])

        if not geno_table.empty:
            vep_path = vep_file_map[chromosomes]
            vep_df = pd.read_csv(vep_path, sep='\t', dtype={'SIFT': str, 'POLYPHEN': str}, low_memory=False)

            # Filter to relevant raw variants
            relevant_vars = vep_df[vep_df['varID'].isin(raw_variant_list)].copy()

            self._logger.info(f"Merging VEP data for {gene_symbol}. BGEN matches: {len(geno_table)} rows.")
            geno_table = pd.merge(relevant_vars, geno_table, on='varID', how="right")

        geno_table.to_csv(variant_file, index=False, sep="\t", na_rep='NA')

        return variant_file, carriers_file_path

    def _process_variant_dosage(self, variant, samples: np.ndarray, variant_info: list, carriers_file: DictWriter):
        """
        Processes dosage information for a given genetic variant, calculates allele-specific metrics,
        and records carrier-specific details to a file.

        The method calculates the alternate allele dosage using genotype probabilities, derives related
        metrics like allele count (AC) and minor allele frequency (MAF), and appends this info to
        the provided variant information list. It also identifies carriers of the alternate allele
        and writes detailed information about these carriers to the specified file.

        :param variant: A genetic variant object containing probabilities, alleles, and other related details.
        :param samples: A list of sample identifiers corresponding to the genotype data.
        :param variant_info: A list to which the calculated variant metrics (e.g., AC, MAF) will be appended.
        :param carriers_file: Path to a file where carrier information for the variant is written.

        Output: A list containing the calculated variant metrics and carrier information.
        """

        # get the genotypes for our variant
        probs = variant.probabilities
        # Calculate dosage (alleles are [REF, ALT])
        alt_dosage = probs[:, 1] + (2 * probs[:, 2])
        # Calculate allele counts
        ac = np.sum(alt_dosage)
        # calculate minor allele frequency
        maf = ac / (2 * len(samples))

        # add data to our list
        variant_info.append({
            'varID': variant.rsid,
            'MAF_tested': maf,
            'AC_tested': ac,
            'AC_tested_Het': np.sum((alt_dosage > 0.5) & (alt_dosage < 1.5)),
            'AC_tested_Hom': np.sum(alt_dosage >= 1.5)
        })

        # Extract Carriers
        carrier_indices = np.where(alt_dosage > 0)[0]
        if len(carrier_indices) > 0:
            ref, alt = variant.alleles[0], variant.alleles[1]
            IID = samples[carrier_indices]
            GT = alt_dosage[carrier_indices]
            # one ID and one GT per loop
            for row in zip(IID, GT):
                current_row = {
                    'CHROM': variant.chrom,
                    'POS': variant.pos,
                    'varID': variant.rsid,
                    'REF': ref,
                    'ALT': alt,
                    'IID': row[0],
                    'GT': row[1]
                }

                carriers_file.writerow(current_row)

    def _run_linear_models(self) -> None:
        """Runs gene-based linear model association tests.

        This method first builds a null model based on the provided phenotype and
        covariates. It then iterates through each chromosome and tarball prefix,
        loading the relevant genetic data and launching parallel jobs to run the
        linear model for each gene. Finally, it collects and processes the
        results, writing them to a summary statistics file.
        """
        null_model = linear_model.linear_model_null(
            phenotype=self._association_pack.pheno_names[0],
            phenofile=self._association_pack.final_covariates,
            is_binary=self._association_pack.is_binary,
            found_quantitative_covariates=self._association_pack.found_quantitative_covariates,
            found_categorical_covariates=self._association_pack.found_categorical_covariates
        )

        thread_utility = ThreadUtility(self._association_pack.threads, thread_factor=1)

        for chromosome, genes in self._genetic_map.items():
            for tarball_prefix in self._association_pack.tarball_prefixes:
                # Load genetic data sequentially for this chunk
                _, genetic_data = linear_model.load_linear_model_genetic_data(
                    tarball_prefix=tarball_prefix,
                    tarball_type=self._association_pack.tarball_type,
                    bgen_prefix=chromosome,
                )

                # Launch parallel jobs for linear model
                for gene_info in genes:
                    thread_utility.launch_job(
                        function=linear_model.run_linear_model,
                        inputs={
                            'linear_model_pack': null_model,
                            'genotype_table': genetic_data,
                            'gene': gene_info.name,
                            'mask_name': tarball_prefix.name,
                            'is_binary': self._association_pack.is_binary,
                            'always_run_corrected': True
                        },
                        outputs=['gene_dict']
                    )

        thread_utility.submit_and_monitor()

        fieldnames = ['ENST', 'mask_name', 'pheno_name', 'p_val_init', 'n_car', 'cMAC', 'n_model',
                      'p_val_full', 'effect', 'std_err', 'model_run']
        if self._association_pack.is_binary:
            fieldnames.extend(['n_noncar_affected', 'n_noncar_unaffected', 'n_car_affected', 'n_car_unaffected'])

        lm_stats_path = Path(f'{self._output_prefix}.lm_stats.tmp')
        with lm_stats_path.open('w') as lm_stats_file:
            lm_stats_writer = csv.DictWriter(lm_stats_file,
                                             delimiter="\t",
                                             fieldnames=fieldnames,
                                             extrasaction='ignore')
            lm_stats_writer.writeheader()
            finished_genes = []
            for result in thread_utility:
                finished_gene: LinearModelResult = result['gene_dict']
                lm_stats_writer.writerow(asdict(finished_gene))
                finished_genes.append(finished_gene)

        process_model_outputs(input_models=finished_genes,
                              output_path=Path(f'{self._output_prefix}.genes.glm.stats.tsv'),
                              tarball_type=self._association_pack.tarball_type,
                              transcripts_table=self._transcripts_table)

    def _run_staar_null_wrapper(self, phenoname: str, phenofile: Path, is_binary: bool,
                                found_quantitative_covariates: List[str],
                                found_categorical_covariates: List[str], sex: int,
                                sparse_kinship_file: Path, sparse_kinship_samples: Path) -> Tuple[
        str, Tuple[str, Path]]:
        """
        Runs the STAAR null model for the specified phenotype. This function serves as a wrapper
        for the STAAR null model computation, incorporating phenotype data, covariates, and
        kinship information to build the model. It facilitates binary or quantitative trait modeling
        based on the input parameters.

        :param phenoname: The name of the phenotype to be processed.
        :param phenofile: Path to the file containing phenotype data.
        :param is_binary: Indicates whether the phenotype is binary or continuous.
        :param found_quantitative_covariates: List of found quantitative covariates to be included in the model.
        :param found_categorical_covariates: List of found categorical covariates to be included in the model.
        :param sex: Sex information for covariate adjustments.
        :param sparse_kinship_file: Path to the file containing sparse kinship matrix.
        :param sparse_kinship_samples: Path to the file containing sample information for sparse kinship matrix.
        :return: A tuple containing the phenotype name and the path to the generated null model file.
        """
        self._logger.info(f"Running STAAR null model for phenotype {phenoname}")
        null_model_path = staar_null(
            phenofile=phenofile,
            phenotype=phenoname,
            is_binary=is_binary,
            found_quantitative_covariates=found_quantitative_covariates,
            found_categorical_covariates=found_categorical_covariates,
            sex=sex,
            sparse_kinship_file=sparse_kinship_file,
            sparse_kinship_samples=sparse_kinship_samples
        )
        return phenoname, null_model_path

    def _export_phenotypes(self) -> Path:
        """Copies the formatted phenotype/covariate file to the output prefix.

        :return: Path to the final phenotype/covariate file.
        """
        out_pheno_path = Path(f'{self._output_prefix}.phenotypes_covariates.formatted.tsv')
        Path('phenotypes_covariates.formatted.txt').rename(out_pheno_path)
        return out_pheno_path

    def _run_staar_models(self) -> None:
        """
        Run STAAR null models for each phenotype and chromosome combination.

        Creates a merged covariates file for STAAR null model and runs the null model
        for each phenotype and chromosome combination.
        """
        valid_staar_chromosomes = set()
        if self._genetic_map:
            with open('staar.gene_list', 'w') as gene_list_file:
                for genes in self._genetic_map.values():
                    for gene_info in genes:
                        gene_list_file.write(gene_info.name + '\n')
                        if gene_info['chrom'] not in valid_staar_chromosomes:
                            valid_staar_chromosomes.add(gene_info['chrom'])

        # Create merged covariates file matching STAAR approach
        self._logger.info("Creating merged covariates file for STAAR null model...")

        first_chrom = next(iter(self._genetic_map.keys()))
        sample_path = self._association_pack.bgen_dict[first_chrom]["sample"].get_file_handle()

        # Read sample file
        sample = pd.read_csv(sample_path, sep=r"\s+", header=0, dtype={'ID_2': str})
        sample = sample.drop(columns=["sex"], errors="ignore")
        sample = sample.iloc[1:].reset_index(drop=True)

        # Read covariates
        covar = pd.read_csv(self._association_pack.final_covariates, sep=' ', header=0, dtype={'IID': str})

        # Merge
        merged = sample.merge(covar, how="left", left_on="ID_2", right_on="IID")
        merged = merged.drop(columns=["ID_1", "missing"], errors="ignore")
        merged = merged.sort_values("ID_2")

        # Remove rows with missing phenotype
        for phenoname in self._association_pack.pheno_names:
            if phenoname in merged.columns:
                merged = merged.dropna(subset=[phenoname])

        # Remove rows with missing covariates
        required_cols = ['age', 'age_squared', 'batch']
        if self._association_pack.sex == 2:
            required_cols.append('sex')
        for i in range(1, 11):
            required_cols.append(f'PC{i}')
        required_cols.extend(self._association_pack.found_quantitative_covariates)
        required_cols.extend(self._association_pack.found_categorical_covariates)

        required_cols = [col for col in required_cols if col in merged.columns]
        merged = merged.dropna(subset=required_cols)

        self._logger.info(f"After removing samples with missing data: {len(merged)} samples remain")

        # Rename and save
        # Drop IID since we're using FID
        merged = merged.drop(columns=['IID', 'FID'], errors='ignore')
        merged = merged.rename(columns={'ID_2': 'FID'})
        merged_cov_path = Path("merged_covariates_for_staar.tsv")
        merged.to_csv(merged_cov_path, sep="\t", index=False)

        thread_utility = ThreadUtility(self._association_pack.threads, thread_factor=1)
        for phenoname in self._association_pack.pheno_names:
            thread_utility.launch_job(
                function=self._run_staar_null_wrapper,
                inputs={
                    'phenoname': phenoname,
                    'phenofile': merged_cov_path,  # Use the new merged file
                    'is_binary': self._association_pack.is_binary,
                    'found_quantitative_covariates': self._association_pack.found_quantitative_covariates,
                    'found_categorical_covariates': self._association_pack.found_categorical_covariates,
                    'sex': self._association_pack.sex,
                    'sparse_kinship_file': self._association_pack.sparse_grm,
                    'sparse_kinship_samples': self._association_pack.sparse_grm_sample
                },
                outputs=['phenotype', 'null_model']
            )
        thread_utility.submit_and_monitor()

        # Collect null models
        null_models = {}
        for result in thread_utility:
            phenotype = result['phenotype']
            null_model = result['null_model']

            # If null_model is a tuple, extract the Path (second element)
            if isinstance(null_model, tuple):
                null_model = null_model[1]  # Get PosixPath from ('T2D', PosixPath(...))

            null_models[phenotype] = null_model

        self._logger.info(f"Collected {len(null_models)} null models: {list(null_models.keys())}")

        # Filter STAAR samples tables to match the samples in the null model
        # Read the samples that were used in the null model
        final_covars = pd.read_csv(merged_cov_path, sep='\t')
        null_model_samples = set(final_covars['FID'].astype(str))

        # Filter each STAAR samples table
        for tarball_prefix in self._association_pack.tarball_prefixes:
            for chromosome in self._genetic_map.keys():
                samples_path = Path(f"{tarball_prefix}.{chromosome}.STAAR.samples_table.tsv")

                if samples_path.exists():
                    # Read the original STAAR samples table
                    staar_samples_df = pd.read_csv(samples_path, sep='\t')
                    original_count = len(staar_samples_df)

                    # Filter to only keep samples in the null model
                    staar_samples_df = staar_samples_df[
                        staar_samples_df['sampID'].astype(str).isin(null_model_samples)
                    ]
                    filtered_count = len(staar_samples_df)

                    # Overwrite with filtered version
                    staar_samples_df.to_csv(samples_path, sep='\t', index=False)

                    self._logger.info(
                        f"Filtered {samples_path.name}: {original_count} → {filtered_count} samples"
                    )

        launcher = joblauncher_factory(download_on_complete=True)

        # Export transcripts table once as it is the same for all jobs
        transcripts_table_path = Path("transcripts_table.tsv")
        self._transcripts_table.to_csv(transcripts_table_path, sep='\t', index=True)
        transcripts_exporter = ExportFileHandler(delete_on_upload=False)
        transcripts_table_file_id = transcripts_exporter.export_files(transcripts_table_path)

        for phenoname in self._association_pack.pheno_names:
            for tarball_prefix in self._association_pack.tarball_prefixes:
                for chromosome in self._genetic_map.keys():
                    staar_data = load_staar_genetic_data(
                        tarball_prefix=tarball_prefix.name,
                        bgen_prefix=chromosome
                    )

                    valid_gene_ids = {gene.name for genes in self._genetic_map.values() for gene in genes}
                    genes_per_chunk = {
                        chunk: [gene for gene in genes.keys() if gene in valid_gene_ids]
                        for chunk, genes in staar_data.items()
                    }

                    for chunk, gene_list in genes_per_chunk.items():
                        if not gene_list:
                            continue

                        subset_staar_data = {chunk: staar_data[chunk]}
                        chunk_json_path = Path(f"{tarball_prefix}.{chunk}.staar_chunk.json")
                        with chunk_json_path.open("w") as f:
                            json.dump(subset_staar_data, f, default=lambda o: list(o) if isinstance(o, set) else o)

                        working_chunk = self._association_pack.bgen_dict[chromosome]

                        exporter = ExportFileHandler(delete_on_upload=False)
                        # null model
                        null_model = exporter.export_files(null_models[phenoname])
                        # staar samples
                        staar_samples = exporter.export_files(f'{tarball_prefix}.{chromosome}.STAAR.samples_table.tsv')
                        # variant table
                        variants_table = exporter.export_files(
                            f'{tarball_prefix}.{chromosome}.STAAR.variants_table.tsv')
                        # chunk file
                        chunk_file = exporter.export_files(chunk_json_path)

                        launcher.launch_job(
                            function=multithread_gene_model,
                            inputs={
                                'null_model': null_model,
                                'pheno_name': phenoname,
                                'tarball_prefix': tarball_prefix.name,
                                'chromosome': chromosome,
                                'genes': gene_list,
                                'chunk_file': chunk_file,
                                'bgen': working_chunk['bgen'].get_input_str(),
                                'index': working_chunk['index'].get_input_str(),
                                'sample': working_chunk['sample'].get_input_str(),
                                'staar_samples': staar_samples,
                                'staar_variants': variants_table,
                                'tarball_type': str(self._association_pack.tarball_type),
                                'transcripts_table': transcripts_table_file_id
                            },
                            outputs=['output_model']
                        )

        launcher.submit_and_monitor()

        completed_staar_chunks = []
        for result in launcher:
            result_file = InputFileHandler(result['output_model']).get_file_handle()
            df = pd.read_csv(result_file, sep='\t', index_col=0)
            completed_staar_chunks.append(df)

        if completed_staar_chunks:
            combined_staar = pd.concat(completed_staar_chunks, axis=0)
            # Merge with transcripts_table to get genomic coordinates
            combined_staar = combined_staar.merge(
                self._transcripts_table[['chrom', 'start', 'end']],
                left_index=True,
                right_index=True,
                how='left'
            )
            combined_staar = combined_staar.sort_values(by='start')
            combined_staar.to_csv(f'{self._output_prefix}.genes.STAAR.stats.tsv', sep='\t', index=True)
            output_tsv = Path(f"{self._output_prefix}.genes.STAAR.stats.tsv")
            outputs = bgzip_and_tabix(output_tsv, skip_row=1, sequence_row=14, begin_row=15, end_row=16)
            self._outputs.extend(outputs)


@dxpy.entry_point('multithread_gene_model')
def multithread_gene_model(null_model, pheno_name, tarball_prefix, chromosome, genes, chunk_file, bgen: str, index: str,
                           sample: str,
                           staar_samples, staar_variants, tarball_type, transcripts_table) -> dict:
    """
    Run a STAAR gene model in a multithreaded way

    :param null_model: a path to the null model RDS file
    :param pheno_name: the phenotype name
    :param tarball_prefix: the tarball prefix to work with
    :param chromosome: the chromosome chunk to work with
    :param genes: list of genes to run
    :param chunk_file: a path to the chunk JSON file (contains the genetic coordinates & variants)
    :param bgen: InputFileHandler for the bgen file
    :param index: InputFileHandler for the bgen index file
    :param sample: InputFileHandler for the bgen sample file
    :param staar_samples: STAAR samples table for the chunk we are working with
    :param staar_variants: STAAR variants table for the chunk we are working with
    :param tarball_type: the tarball type (TarballType enum)
    :param transcripts_table: a path to the transcripts table
    :return: Path to the output STAAR results TSV file (post-annotation)
    """

    # load our VM environment
    cmd_executor = build_default_command_executor()
    null_model = InputFileHandler(null_model).get_file_handle()
    staar_samples = InputFileHandler(staar_samples).get_file_handle()
    staar_variants = InputFileHandler(staar_variants).get_file_handle()
    chunk_file = InputFileHandler(chunk_file).get_file_handle()
    transcripts_table = InputFileHandler(transcripts_table).get_file_handle()

    with open(chunk_file, "r") as f:
        staar_data = json.load(f)

    # download our bgen files
    bgen_path = InputFileHandler(bgen, download_now=True).get_file_handle()
    index_path = InputFileHandler(index, download_now=True).get_file_handle()
    sample_path = InputFileHandler(sample, download_now=True).get_file_handle()

    thread_utility = ThreadUtility()

    for gene in genes:
        # Check if gene exists in staar_data
        if gene not in staar_data[chromosome]:
            LOGGER.warning(f"Gene {gene} not found in staar_data for {chromosome}")
            continue

        gene_info = staar_data[chromosome][gene]
        n_variants = len(gene_info.get('vars', []))

        # Skip genes with fewer than 2 variants
        if n_variants < 2:
            LOGGER.warning(f"Skipping {gene}: fewer than 2 variants ({n_variants})")
            continue

        LOGGER.info(f"Processing gene {gene} with {n_variants} variants")

        # Read the filtered samples table
        staar_samples_df = pd.read_csv(staar_samples, sep='\t')
        keep_rows = staar_samples_df['row'].values

        # generate a csr matrix from the bgen files
        matrix, summary_dict = generate_csr_matrix_from_bgen(
            bgen_path=bgen_path,
            sample_path=sample_path,
            variant_filter_list=staar_data[chromosome][gene]['vars'],
            chromosome=staar_data[chromosome][gene]['chrom'],
            start=staar_data[chromosome][gene]['min'],
            end=staar_data[chromosome][gene]['max'],
            should_collapse_matrix=False
        )

        # export matrix to file
        # Subset matrix to filtered samples
        matrix = matrix[keep_rows, :]
        # Then save and use
        mmwrite(f"{tarball_prefix}.{chromosome}.STAAR.mtx", matrix)

        thread_utility.launch_job(
            function=staar_genes,
            inputs={
                'staar_null_path': null_model,
                'pheno_name': pheno_name,
                'gene': gene,  # single ENST ID string
                'mask_name': tarball_prefix,
                'staar_matrix': f"{tarball_prefix}.{chromosome}.STAAR.mtx",
                'staar_samples': staar_samples,
                'staar_variants': staar_variants,
                'out_dir': Path('.'),
            },
            outputs=['staar_result']
        )
    thread_utility.submit_and_monitor()
    # Print a preliminary STAAR output
    completed_staar_files = []
    # And gather the resulting futures
    for result in thread_utility:
        # Each result is a dict with {'staar_result': STAARModelResult(...)}
        staar_result = result["staar_result"]
        completed_staar_files.append(staar_result)

    # Annotate STAAR output
    transcript = pd.read_csv(transcripts_table, sep='\t', index_col=0)
    output_model = Path(f'{chromosome}.staar_results.tsv')
    process_model_outputs(input_models=completed_staar_files,
                          output_path=output_model,
                          tarball_type=tarball_type,
                          transcripts_table=transcript)

    exporter = ExportFileHandler()
    uploaded_file = exporter.export_files(output_model)

    return {"output_model": uploaded_file}
